export const CHAMPIONSHIP_EVENTS = Object.freeze({
  PROFILE_ACCEPTED: "PROFILE_ACCEPTED",
  GATE_SELECTED: "GATE_SELECTED",
  HUNTER_MOVED: "HUNTER_MOVED",
  HUNTER_BLOCKED: "HUNTER_BLOCKED",
  WILD_ENCOUNTER_STARTED: "WILD_ENCOUNTER_STARTED",
  CAPTURE_PREPARED: "CAPTURE_PREPARED",
  CAPTURE_COMPLETED: "CAPTURE_COMPLETED",
  COLLECTION_OPENED: "COLLECTION_OPENED",
  SHOP_OPENED: "SHOP_OPENED",
  RESEARCH_PURCHASED: "RESEARCH_PURCHASED",
  ARENA_OPENED: "ARENA_OPENED",
  BATTLE_STARTED: "BATTLE_STARTED",
  BATTLE_TURN_RESOLVED: "BATTLE_TURN_RESOLVED",
  BATTLE_COMPLETED: "BATTLE_COMPLETED",
  RESEARCH_COMPLETED: "RESEARCH_COMPLETED"
});

export function createEventDescriptor(type, payload = {}, evidenceRefs = [], parityStatus = "RESEARCH_NON_PARITY") {
  return { type, payload, evidenceRefs, parityStatus };
}
